name: Workflow Demo

on: 
  push

env:
  ACCESS_ID: ${{ vars.ACCESS_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACCESS_ID: 'kode-kloud-123456'
    steps:
    - name: Echo ACCESS_ID
      run: echo $ACCESS_ID
